apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-loader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-loader
  template:
    metadata:
      labels:
        app: data-loader
    spec:
      containers:
        - name: data-loader
          image: danc12/mongo-open1
          ports:
            - containerPort: 8080